[package]
org = "ayesha"
name = "arxiv"
version = "0.5.2"
distribution = "2201.13.0"
keywords = ["arxiv", "research", "papers", "search"]
license = ["Apache-2.0"]
icon = "icon.png"
readme = "Package.md"
repository = "https://github.com/ayeshLK/module-arxiv"

[build-options]
observabilityIncluded = true
